#!/bin/bash
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | stdbuf -o0 grep '^workspace>>' | stdbuf -o0 awk -F '>>|,' '{print $2}' | while read -r line; do

  if [[ "$line" -eq "discord" ]]; then
    echo ﭮ" "
  else
    echo $line
  fi
done
