#!/bin/bash

socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | stdbuf -o0 grep -P 'workspace>>[\w\W]+|movewindow>>[\w\W]+' | stdbuf -o0 awk -F '>>|,' '{print $2}' | \
echo $( hyprctl -j workspaces | jq  "sort_by(.id) | map({name:.name, active:(if .name == `hyprctl activewindow -j | jq ".workspace.name" ` then true else false end)})" )
