def setup(c):
    c.colors.webpage.preferred_color_scheme = "dark"

    c.colors.completion.category.bg = "{{color.dark.surface_container}}"
    c.colors.completion.category.border.bottom = "{{color.dark.surface_container}}"
    c.colors.completion.category.border.top = "{{color.dark.outline_variant}}"
    c.colors.completion.category.fg = "{{color.dark.primary}}"
    c.colors.completion.even.bg = "{{color.dark.surface_container_low}}"
    c.colors.completion.odd.bg = "{{color.dark.surface_container_low}}"
    c.colors.completion.fg = "{{color.dark.on_surface}}"
    c.colors.completion.item.selected.bg = "{{color.dark.secondary_container}}"
    c.colors.completion.item.selected.border.bottom = "{{color.dark.secondary_container}}"
    c.colors.completion.item.selected.border.top = "{{color.dark.secondary_container}}"
    c.colors.completion.item.selected.fg = "{{color.dark.on_secondary_container}}"
    c.colors.completion.item.selected.match.fg = "{{color.dark.primary}}"
    c.colors.completion.match.fg = "{{color.dark.primary}}"
    c.colors.completion.scrollbar.bg = "{{color.dark.surface_container_lowest}}"
    c.colors.completion.scrollbar.fg = "{{color.dark.outline}}"

    c.colors.downloads.bar.bg = "{{color.dark.surface_container_low}}"
    c.colors.downloads.error.bg = "{{color.dark.error_container}}"
    c.colors.downloads.error.fg = "{{color.dark.on_error_container}}"
    c.colors.downloads.start.bg = "{{color.dark.primary_container}}"
    c.colors.downloads.start.fg = "{{color.dark.on_primary_container}}"
    c.colors.downloads.stop.bg = "{{color.dark.tertiary_container}}"
    c.colors.downloads.stop.fg = "{{color.dark.on_tertiary_container}}"
    c.colors.downloads.system.bg = "none"
    c.colors.downloads.system.fg = "none"

    c.colors.hints.bg = "{{color.dark.primary}}"
    c.colors.hints.fg = "{{color.dark.on_primary}}"
    c.colors.hints.match.fg = "{{color.dark.primary_container}}"
    c.hints.border = "1px solid {{color.dark.outline}}"

    c.colors.keyhint.bg = "{{color.dark.surface_container}}"
    c.colors.keyhint.fg = "{{color.dark.on_surface}}"
    c.colors.keyhint.suffix.fg = "{{color.dark.primary}}"

    c.colors.messages.error.bg = "{{color.dark.error_container}}"
    c.colors.messages.error.border = "{{color.dark.error}}"
    c.colors.messages.error.fg = "{{color.dark.on_error_container}}"
    c.colors.messages.info.bg = "{{color.dark.primary_container}}"
    c.colors.messages.info.border = "{{color.dark.primary}}"
    c.colors.messages.info.fg = "{{color.dark.on_primary_container}}"
    c.colors.messages.warning.bg = "{{color.dark.tertiary_container}}"
    c.colors.messages.warning.border = "{{color.dark.tertiary}}"
    c.colors.messages.warning.fg = "{{color.dark.on_tertiary_container}}"

    c.colors.prompts.bg = "{{color.dark.surface_container}}"
    c.colors.prompts.border = "1px solid {{color.dark.outline}}"
    c.colors.prompts.fg = "{{color.dark.on_surface}}"
    c.colors.prompts.selected.bg = "{{color.dark.secondary_container}}"
    c.colors.prompts.selected.fg = "{{color.dark.on_secondary_container}}"

    c.colors.statusbar.normal.bg = "{{color.dark.surface_container_low}}"
    c.colors.statusbar.normal.fg = "{{color.dark.on_surface}}"
    c.colors.statusbar.insert.bg = "{{color.dark.primary_container}}"
    c.colors.statusbar.insert.fg = "{{color.dark.on_primary_container}}"
    c.colors.statusbar.command.bg = "{{color.dark.surface_container}}"
    c.colors.statusbar.command.fg = "{{color.dark.on_surface}}"
    c.colors.statusbar.caret.bg = "{{color.dark.tertiary_container}}"
    c.colors.statusbar.caret.fg = "{{color.dark.on_tertiary_container}}"
    c.colors.statusbar.caret.selection.bg = "{{color.dark.tertiary_container}}"
    c.colors.statusbar.caret.selection.fg = "{{color.dark.on_tertiary_container}}"
    c.colors.statusbar.passthrough.bg = "{{color.dark.secondary_container}}"
    c.colors.statusbar.passthrough.fg = "{{color.dark.on_secondary_container}}"
    c.colors.statusbar.private.bg = "{{color.dark.surface_container_high}}"
    c.colors.statusbar.private.fg = "{{color.dark.on_surface_variant}}"
    c.colors.statusbar.command.private.bg = "{{color.dark.surface_container_high}}"
    c.colors.statusbar.command.private.fg = "{{color.dark.on_surface_variant}}"
    c.colors.statusbar.progress.bg = "{{color.dark.primary}}"
    c.colors.statusbar.url.error.fg = "{{color.dark.error}}"
    c.colors.statusbar.url.fg = "{{color.dark.on_surface}}"
    c.colors.statusbar.url.hover.fg = "{{color.dark.primary}}"
    c.colors.statusbar.url.success.http.fg = "{{color.dark.tertiary}}"
    c.colors.statusbar.url.success.https.fg = "{{color.dark.primary}}"
    c.colors.statusbar.url.warn.fg = "{{base16.dark.base0A}}"

    c.colors.tabs.bar.bg = "{{color.dark.surface_container_lowest}}"
    c.colors.tabs.even.bg = "{{color.dark.surface_container}}"
    c.colors.tabs.odd.bg = "{{color.dark.surface_container}}"
    c.colors.tabs.even.fg = "{{color.dark.on_surface_variant}}"
    c.colors.tabs.odd.fg = "{{color.dark.on_surface_variant}}"
    c.colors.tabs.selected.even.bg = "{{color.dark.surface_container_high}}"
    c.colors.tabs.selected.odd.bg = "{{color.dark.surface_container_high}}"
    c.colors.tabs.selected.even.fg = "{{color.dark.on_surface}}"
    c.colors.tabs.selected.odd.fg = "{{color.dark.on_surface}}"
    c.colors.tabs.indicator.error = "{{color.dark.error}}"
    c.colors.tabs.indicator.system = "none"

    c.colors.contextmenu.menu.bg = "{{color.dark.surface_container_low}}"
    c.colors.contextmenu.menu.fg = "{{color.dark.on_surface}}"
    c.colors.contextmenu.disabled.bg = "{{color.dark.surface_container_lowest}}"
    c.colors.contextmenu.disabled.fg = "{{color.dark.on_surface_variant}}"
    c.colors.contextmenu.selected.bg = "{{color.dark.secondary_container}}"
    c.colors.contextmenu.selected.fg = "{{color.dark.on_secondary_container}}"
