#!/bin/bash

cd ~

# XDG Specifications
export XDG_CURRENT_DESKTOP=Hyprland
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=Hyprland

# QT Variables
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_QPA_PLATFORM="wayland;xcb"
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export QT_QPA_PLATFORMTHEME=qt5ct

# NVIDIA Specific
export GBM_BACKEND=nvidia-drm
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export LIBVA_DRIVER_NAME=nvidia
export WLR_DRM_NO_ATOMIC=1
export __GL_VRR_ALLOWED=0


export MOZ_ENABLE_WAYLAND=1
export WLR_NO_HARDWARE_CURSORS=1

# Log
export HYPRLAND_LOG_WLR=1


# Cursor 
export XCURSOR_THEME=Bibata-Modern-Classic
export XCURSOR_SIZE=24

# IME Support
export GTK_IM_MODULE=fcitx
export QT_IN_MODULE=fcitx
export XMODIFIRES=@im=fcitx
export SDL_IM_MODULE=fcitx
export GLFW_IM_MODULE=fcitx

exec Hyprland
